version: "3.9"
services:
  db:
    # container_name: therapy-link-mysql
    platform: linux/amd64 # Only required in case Apple M1 / ARM
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql:8.0.27"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=social
      - MYSQL_ROOT_PASSWORD=social
    volumes:
      - database-data:/var/lib/mysql # persist data even if container shuts

  api:
    build: .
    ports:
      - "8080:80"
    env_file: .env
    depends_on:
      - db
    restart: on-failure # require because mysql might take couple of seconds to be ready to accept connectsions
    volumes:
      - .:/code

volumes:
  database-data: null # named volumes can be managed easier using docker-compose  
